### ISSUE TITLE
Slack alert action does not work, when "equals 0" trigger parameter is in use and "Fields" are defined in that Slack alert action.

### ISSUE THREAD

**Issue by BartekZm** [splunk/slack-alerts#31]
**Describe the bug**
Slack alert action does not work, when "equals 0" trigger parameter is in use and "Fields" are defined in that Slack alert action.

**To Reproduce**
1. Create a saved search with alert trigger "equals 0" parameter.
2. Add Slack alert action, define any field in the "Fields" field (eg. index, sourcetype)
3. The alert action fails to be triggered (=no message in Slack). In Splunk "sendmodalert" thread you will see the following traceback:
`Unexpected error:<class 'AttributeError'>
Traceback (most recent call last):
File "/opt/splunk/etc/apps/slack_alerts/bin/slack.py", line 117, in send_slack_message
json.dumps(build_slack_message(payload))
File "/opt/splunk/etc/apps/slack_alerts/bin/slack.py", line 97, in build_slack_message
params['attachments'] = [dict(fields=build_fields_attachment(payload))]
File "/opt/splunk/etc/apps/slack_alerts/bin/slack.py", line 27, in build_fields_attachment
available_fields = list(res.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
Alert action failed
Alert action script completed in duration=31 ms with exit code=6`

**Expected behavior**
Slack alert should be triggered when "fields" are listed and "equals 0" is used as a trigger condition.

**Screenshots**
<img width="788" alt="Screenshot 2022-08-24 at 12 15 17" src="https://user-images.githubusercontent.com/78498132/186859338-981b2039-5bd7-4ea3-a131-5df6b17f873f.png">
<img width="800" alt="Screenshot 2022-08-24 at 11 09 22" src="https://user-images.githubusercontent.com/78498132/186859401-e60ef521-642a-45e8-b7f0-861961d51821.png">

**Splunk Environment:**
 - Splunk Version: 8.2.2203.3
 - OS: Linux
 - Cloud: Splunk Cloud

**Additional context**
Workarounds:
1. Don't define any "Fields" in the Slack alert action, when the alert trigger condition is set to "equals 0".
2. When you need to specify "Fields" in the Slack alert action, use any different trigger condition but the "equals 0".

**Comment by leandropadua** [comment]
we are getting spammed with errors 
> AttributeError: 'NoneType' object has no attribute 'keys'

Any chance this error can be fixed. There's an open PR for it. Thanks
